// ═══════════════════════════════════════════════════════════
// KRISHNA — Root Build File
// GRADLE 7.5 + AGP 7.4.2  (JDK 11 aur JDK 17 — dono par chalega)
// Yeh combo phone par Android IDE app se bhi build hota hai.
// ═══════════════════════════════════════════════════════════
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
